# Generated by Django 4.2.5 on 2026-03-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0068_remove_city_hospital_bills_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsinventory',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='hospital.inventory'),
        ),
    ]
