# Generated by Django 4.2.5 on 2026-04-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0070_remove_city_hospital_city_region_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailscomposeingredient',
            unique_together=set(),
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
    ]
