# Generated by Django 4.2.5 on 2026-04-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0071_alter_detailscomposeingredient_unique_together_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.AlterField(
            model_name='cash',
            name='type_cash',
            field=models.CharField(blank=True, choices=[('CASH_COUNTERS', 'CASH_COUNTERS'), ('CASH_MAIN', 'CASH_MAIN'), ('CASH_BANK', 'CASH_BANK'), ('CASH', 'Cash'), ('MOMO', 'MTN MoMo'), ('OM', 'Orange Money')], max_length=255, null=True),
        ),
    ]
