# Generated by Django 4.2.5 on 2026-04-15 20:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0073_alter_detailsinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name_language', models.JSONField(blank=True, default=list, null=True)),
                ('price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delivery', models.BooleanField(default=True, null=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='hospital.dish')),
            ],
            options={
                'db_table': 'combo_menu',
                'ordering': ('-id',),
            },
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
        migrations.CreateModel(
            name='DetailsComboMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('combo_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_menus', to='hospital.combomenu')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.dish')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'details_combo_menu',
                'ordering': ('-createdAt',),
            },
        ),
        migrations.AddField(
            model_name='detailsbills',
            name='combo_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.combomenu'),
        ),
        migrations.AddField(
            model_name='structurearticle',
            name='combo_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_combos', to='hospital.combomenu'),
        ),
        migrations.CreateModel(
            name='ComboMenuTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_shared', models.BooleanField(default=False, null=True)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('combo_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospital.combomenu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'combo_menu_translation',
                'unique_together': {('combo_menu', 'language')},
            },
        ),
    ]
