# Generated by Django 4.2.5 on 2026-04-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0075_remove_city_hospital_city_region_combomenu_user'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='hospital',
        # ),
        migrations.RemoveField(
            model_name='combomenu',
            name='price',
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='region',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.region'),
        # ),
    ]
