# Generated by Django 4.2.5 on 2026-04-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0076_remove_city_hospital_remove_combomenu_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combomenu',
            name='dish',
        )
    ]
